import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, ArrowLeft, CheckCircle2, ClipboardList, Loader2, ShieldCheck } from 'lucide-react';
import { PageHeader } from '../components/layout/PageHeader';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { annotationService } from '../services/annotationService';
import { useAuth } from '../context/AuthContext';

const titleize = (value) => String(value || '—').replaceAll('_', ' ');
const canAdjudicate = (role = '') => /manager|admin|lead/i.test(role);
const fields = ['sif_potential', 'sif_precursor', 'primary_hazard', 'activity', 'primary_precursor', 'life_saving_rule'];

function Submission({ title, submission }) {
  return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-2 text-xs">{fields.map((field) => <div key={field} className="flex justify-between gap-3 border-b border-surface-border/50 pb-2"><span className="font-bold text-ink-muted">{titleize(field)}</span><span className="text-right font-semibold text-ink-primary">{titleize(submission?.[field])}</span></div>)}<div><p className="font-bold text-ink-muted">Evidence</p>{(submission?.evidence_spans || []).map((s, i) => <p key={i} className="mt-1 rounded-lg bg-canvas-subtle p-2 text-ink-primary">“{s.text}”</p>) || '—'}</div><div><p className="font-bold text-ink-muted">Notes</p><p className="mt-1 text-ink-primary whitespace-pre-wrap">{submission?.notes || '—'}</p></div></CardContent></Card>;
}

export function AnnotationAdjudication() {
  const { currentUser } = useAuth(); const navigate = useNavigate(); const [queue, setQueue] = useState([]); const [quality, setQuality] = useState(null); const [readiness, setReadiness] = useState(null); const [detail, setDetail] = useState(null); const [notes, setNotes] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(''); try { const [disagreements, report, release] = await Promise.all([annotationService.disagreements(currentUser.userId), annotationService.quality(), annotationService.releaseReadiness()]); setQueue(disagreements); setQuality(report); setReadiness(release); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { if (canAdjudicate(currentUser?.role)) load(); }, [currentUser?.userId]);
  const open = async (taskId) => { try { setDetail(await annotationService.disagreement(currentUser.userId, taskId)); setNotes(''); } catch (e) { setError(e.message); } };
  const resolve = async () => { if (!detail) return; const a = detail.submission_a; const payload = { resolved_sif_potential: a.sif_potential, resolved_sif_precursor: a.sif_precursor, resolved_primary_hazard: a.primary_hazard, resolved_secondary_hazards: a.secondary_hazards || [], resolved_activity: a.activity, resolved_primary_precursor: a.primary_precursor, resolved_precursor_categories: a.precursor_categories || [], resolved_life_saving_rule: a.life_saving_rule, resolved_life_saving_rules: a.life_saving_rules || [], resolved_barriers: a.barriers || [], resolved_evidence_spans: a.evidence_spans || [], adjudication_notes: notes }; setSaving(true); try { await annotationService.adjudicate(currentUser.userId, detail.task_id, payload); setDetail(null); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  if (!canAdjudicate(currentUser?.role)) return <div className="p-12 text-center"><ShieldCheck className="mx-auto w-10 h-10 text-amber-700" /><h1 className="mt-3 text-lg font-black text-ink-primary">Adjudicator access required</h1><p className="mt-1 text-xs text-ink-muted">Independent annotations remain protected from annotators.</p></div>;
  if (loading) return <div className="p-16 text-center"><Loader2 className="mx-auto w-8 h-8 animate-spin text-emerald-700" /></div>;
  return <div className="space-y-6"><PageHeader title="Annotation Quality & Adjudication" subtitle="Authorized lead view. Independent annotations are displayed only after both submissions are final." actions={<Button variant="secondary" size="sm" icon={ArrowLeft} onClick={() => navigate('/annotations')}>Back to workbench</Button>} />{error && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-xs text-red-800">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Paired annotations', quality?.total_paired_records], ['Cohen’s kappa', quality?.overall_cohens_kappa], ['Precursor Jaccard', quality?.multilabel_precursor_jaccard], ['Evidence span IoU', quality?.evidence_span_iou]].map(([label, value]) => <Card key={label}><CardContent className="p-4"><p className="text-2xl font-black text-ink-primary">{value ?? '—'}</p><p className="text-[10px] font-bold uppercase text-ink-muted">{label}</p></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle subtitle={`${quality?.unresolved_disagreements_count || 0} unresolved field differences`}>Disagreement queue</CardTitle></CardHeader><CardContent className="p-0 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-canvas-subtle text-[10px] uppercase tracking-wide text-ink-muted"><tr><th className="p-4">Report</th><th className="p-4">Field</th><th className="p-4">Annotator A</th><th className="p-4">Annotator B</th><th className="p-4"></th></tr></thead><tbody>{queue.length ? queue.map((d) => <tr key={d.id} className="border-t border-surface-border"><td className="p-4 font-mono font-bold">{d.report_id}</td><td className="p-4">{titleize(d.field_name)}</td><td className="p-4">{Array.isArray(d.annotator_a_value) ? d.annotator_a_value.length + ' values' : titleize(d.annotator_a_value)}</td><td className="p-4">{Array.isArray(d.annotator_b_value) ? d.annotator_b_value.length + ' values' : titleize(d.annotator_b_value)}</td><td className="p-4"><Button size="xs" onClick={() => open(d.task_id)}>Adjudicate</Button></td></tr>) : <tr><td colSpan="5" className="p-10 text-center text-ink-muted">No unresolved disagreements.</td></tr>}</tbody></table></CardContent></Card>
    <Card><CardHeader><CardTitle subtitle="Read-only backend gate audit. This screen cannot release a dataset.">Release readiness</CardTitle></CardHeader><CardContent className="space-y-2">{(readiness?.gates || []).map((gate) => <div key={gate.gate_name} className="flex gap-3 rounded-xl border border-surface-border p-3 text-xs"><span className={`mt-0.5 h-2.5 w-2.5 rounded-full ${gate.passed ? 'bg-emerald-600' : gate.severity === 'WARNING' ? 'bg-amber-500' : 'bg-red-600'}`} /><div><b className="text-ink-primary">{gate.title}</b><p className="mt-0.5 text-ink-muted">{gate.details}</p></div></div>)}</CardContent></Card>
    {detail && <Card><CardHeader action={<Button variant="outline" size="xs" onClick={() => setDetail(null)}>Close</Button>}><CardTitle>Adjudication: {detail.report_id}</CardTitle></CardHeader><CardContent className="space-y-5"><p className="rounded-xl bg-canvas-subtle p-4 text-xs leading-6 text-ink-primary">{detail.raw_text}</p><div className="grid gap-4 lg:grid-cols-2"><Submission title="Annotator A" submission={detail.submission_a} /><Submission title="Annotator B" submission={detail.submission_b} /></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-950"><b>Differences:</b> {detail.disagreements.map((d) => titleize(d.field_name)).join(', ')}</div><label className="block"><span className="text-xs font-extrabold text-ink-primary">Adjudication notes</span><textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows="3" className="mt-1.5 w-full rounded-xl border border-surface-border p-3 text-xs" placeholder="Explain the evidence and final decision…" /></label><p className="text-[11px] text-ink-muted">Resolution initially uses Annotator A’s values. Review the fields above and document the final decision before resolving.</p><Button icon={CheckCircle2} isLoading={saving} disabled={notes.trim().length < 5} onClick={resolve}>Resolve as adjudicated</Button></CardContent></Card>}
  </div>;
}
